/* Study Hub service worker
   ------------------------
   Precaches the entire site on install so it works fully offline once
   visited. Strategy:
     • HTML pages + subject.js  → network-first (you see edits immediately
       when online, cached copy when offline)
     • fonts / css / js / icons → cache-first (they never change)

   NOTE FOR EDITING: this file is regenerated by tools/build-sw.js — run
   `node tools/build-sw.js` after adding/removing files (e.g. new week
   pages or a new subject folder). Editing existing files needs nothing:
   network-first picks changes up automatically.
*/
"use strict";

var CACHE = "studyhub-v6";

var PRECACHE = [
  "./",
  "README.html",
  "assets/fonts/ibm-plex-mono-latin-400-normal.woff2",
  "assets/fonts/ibm-plex-mono-latin-500-normal.woff2",
  "assets/fonts/ibm-plex-mono-latin-600-normal.woff2",
  "assets/fonts/ibm-plex-sans-latin-400-normal.woff2",
  "assets/fonts/ibm-plex-sans-latin-500-normal.woff2",
  "assets/fonts/ibm-plex-sans-latin-600-normal.woff2",
  "assets/fonts/ibm-plex-sans-latin-700-normal.woff2",
  "assets/hub.js",
  "assets/katex/auto-render.min.js",
  "assets/katex/fonts/KaTeX_AMS-Regular.woff2",
  "assets/katex/fonts/KaTeX_Caligraphic-Bold.woff2",
  "assets/katex/fonts/KaTeX_Caligraphic-Regular.woff2",
  "assets/katex/fonts/KaTeX_Fraktur-Bold.woff2",
  "assets/katex/fonts/KaTeX_Fraktur-Regular.woff2",
  "assets/katex/fonts/KaTeX_Main-Bold.woff2",
  "assets/katex/fonts/KaTeX_Main-BoldItalic.woff2",
  "assets/katex/fonts/KaTeX_Main-Italic.woff2",
  "assets/katex/fonts/KaTeX_Main-Regular.woff2",
  "assets/katex/fonts/KaTeX_Math-BoldItalic.woff2",
  "assets/katex/fonts/KaTeX_Math-Italic.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Bold.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Italic.woff2",
  "assets/katex/fonts/KaTeX_SansSerif-Regular.woff2",
  "assets/katex/fonts/KaTeX_Script-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size1-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size2-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size3-Regular.woff2",
  "assets/katex/fonts/KaTeX_Size4-Regular.woff2",
  "assets/katex/fonts/KaTeX_Typewriter-Regular.woff2",
  "assets/katex/katex.min.css",
  "assets/katex/katex.min.js",
  "assets/styles.css",
  "engg2440/assessments.html",
  "engg2440/equations.html",
  "engg2440/glossary.html",
  "engg2440/index.html",
  "engg2440/search.html",
  "engg2440/subject.js",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "index.html",
  "manifest.webmanifest",
  "mech2430/assessments.html",
  "mech2430/equations.html",
  "mech2430/glossary.html",
  "mech2430/index.html",
  "mech2430/search.html",
  "mech2430/subject.js",
  "mech2430/week-01.html",
  "mech2430/week-02.html",
  "mech2430/week-03.html",
  "mech2430/week-05.html",
  "mech2430/week-06.html",
  "mech2430/week-07.html",
  "mech2430/week-09.html",
  "mech2430/week-10.html",
  "mech2430/week-11.html",
  "mech3695/assessments.html",
  "mech3695/equations.html",
  "mech3695/glossary.html",
  "mech3695/index.html",
  "mech3695/search.html",
  "mech3695/subject.js",
  "mech3695/week-01.html",
  "mech3695/week-02.html",
  "mech3695/week-03.html",
  "mech3695/week-04.html",
  "mech3695/week-05.html",
  "mech3695/week-06.html",
  "mech3695/week-07.html",
  "mech3695/week-09.html",
  "mech3695/week-10.html",
  "mech3695/week-11.html",
  "mech3720/assessments.html",
  "mech3720/equations.html",
  "mech3720/glossary.html",
  "mech3720/index.html",
  "mech3720/search.html",
  "mech3720/subject.js",
  "mech3780/assessments.html",
  "mech3780/equations.html",
  "mech3780/glossary.html",
  "mech3780/index.html",
  "mech3780/search.html",
  "mech3780/subject.js"
];

/* HTML and subject data get network-first so edits show up */
function isContent(url) {
  return /\.html$/.test(url.pathname) ||
         /subject\.js$/.test(url.pathname) ||
         url.pathname.endsWith("/");
}

self.addEventListener("install", function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) { return c.addAll(PRECACHE); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; })
        .map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function (e) {
  var url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;

  if (isContent(url)) {
    /* network-first, fall back to cache (strip ?q= etc. when matching) */
    e.respondWith(
      fetch(e.request).then(function (res) {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
        return res;
      }).catch(function () {
        return caches.match(e.request, { ignoreSearch: true });
      })
    );
  } else {
    /* cache-first for immutable assets */
    e.respondWith(
      caches.match(e.request).then(function (hit) {
        return hit || fetch(e.request).then(function (res) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
          return res;
        });
      })
    );
  }
});
