/* ============================================================
   ENGG2300 — Engineering Fluid Mechanics   ·  SUBJECT DATA FILE
   ------------------------------------------------------------
   ARCHIVED subject, kept as a reference. Assessments and dates are
   deliberately empty — the notes, equation sheet and glossary are
   the useful part. MECH3780 builds directly on this material.

   Convention used across this hub: every symbol appearing in an
   equation's latex is listed in its `vars`, and every var carries an
   href to its glossary entry (which also gives the hover definition).
   ============================================================ */
const R = String.raw;   // lets you write LaTeX with single backslashes

window.SUBJECT = {

  meta:{
    code:"ENGG2300",
    title:"Engineering Fluid Mechanics",
    inst:"University of Newcastle · Callaghan",
    term:"Completed",
    coordinator:"A/Prof Mahshid Firouzi (CFD week by Dr Zhengbiao Peng)",
    text:"Çengel & Cimbala — Fluid Mechanics: Fundamentals and Applications (4th ed.); White — Fluid Mechanics; Escudier — Introduction to Engineering Fluid Mechanics",
    weekOneMonday:"2025-07-28"   // nominal only — nothing is date-driven here
  },

  nav:[
    {label:"Subject", links:[
      {t:"Dashboard",   f:"index.html",       icon:"home"},
      {t:"Equations",   f:"equations.html",   icon:"eq"},
      {t:"Glossary",    f:"glossary.html",    icon:"book"},
      {t:"Search",      f:"search.html",      icon:"search"}
    ]}
  ],

  /* =========================================================
     WEEKLY CONTENT PAGES
     ========================================================= */
  pages:[
    {
      f:"week-01.html", week:1,
      t:"Pressure Distribution in a Fluid",
      summary:"The vocabulary of the whole subject: what a fluid is, intensive versus extensive properties, density, specific gravity and specific weight, and dynamic versus kinematic viscosity. Then pressure — absolute, gauge and vacuum — the hydrostatic relation p = ρgh and the idea of pressure head, Pascal's law and why pressure at a point is the same in all directions, and the classic applications: the hydraulic press, the barometer and the U-tube manometer.",
      keywords:"fluid liquid gas fluid statics dynamics property intensive extensive density specific gravity specific weight viscosity dynamic kinematic stoke newtonian inviscid viscous no-slip pressure pascal bar atm psi mmHg torr absolute gauge vacuum atmospheric hydrostatic pressure depth head pascal law hydraulic press barometer mercury manometer u-tube",
      related:[
        {type:"eq", label:"Density & specific gravity",  href:"equations.html#eq-density"},
        {type:"eq", label:"Viscosity",                   href:"equations.html#eq-viscosity"},
        {type:"eq", label:"Hydrostatic pressure",        href:"equations.html#eq-hydrostatic"},
        {type:"eq", label:"Gauge & absolute pressure",   href:"equations.html#eq-gauge"},
        {type:"eq", label:"Hydraulic press",             href:"equations.html#eq-hydraulic-press"},
        {type:"eq", label:"Manometer",                   href:"equations.html#eq-manometer"},
        {type:"def",label:"Pressure",                    href:"glossary.html#g-pressure"},
        {type:"def",label:"Viscosity",                   href:"glossary.html#g-viscosity"},
        {type:"def",label:"Pascal's law",                href:"glossary.html#g-pascal"}
      ]
    },
    {
      f:"week-02.html", week:2,
      t:"Hydrostatic Forces &amp; Buoyancy",
      summary:"Integrating the hydrostatic pressure distribution over a submerged surface. The resultant force on a plane surface is the centroid pressure times the area, but it acts below the centroid at the centre of pressure — located with the second moment of area. Curved surfaces are handled by resolving into horizontal and vertical components. Then buoyancy: Archimedes' principle, the centre of buoyancy, and the metacentre that decides whether a floating body is stable.",
      keywords:"hydrostatic force submerged plane surface resultant force centroid centre of pressure second moment of area parallel axis inclined gate hinge moment balance curved surface horizontal vertical component buoyancy buoyant force archimedes principle displaced volume centre of buoyancy floating body stability metacentre metacentric height overturning righting moment",
      related:[
        {type:"eq", label:"Force on a plane surface",    href:"equations.html#eq-hydrostatic-force"},
        {type:"eq", label:"Centre of pressure",          href:"equations.html#eq-centre-pressure"},
        {type:"eq", label:"Buoyant force",               href:"equations.html#eq-buoyancy"},
        {type:"def",label:"Centre of pressure",          href:"glossary.html#g-centre-pressure"},
        {type:"def",label:"Buoyancy",                    href:"glossary.html#g-buoyancy"},
        {type:"def",label:"Metacentre",                  href:"glossary.html#g-metacentre"}
      ]
    },
    {
      f:"week-03.html", week:3,
      t:"Continuity &amp; the Bernoulli Equation",
      summary:"Moving from statics to motion. Classifying flows — steady or unsteady, laminar or turbulent, viscous or inviscid — and the Reynolds number that decides the second of those. Streamlines and streamtubes, the Reynolds transport theorem that converts system laws into control-volume laws, and from it conservation of mass (continuity) and the linear momentum equation. Finally the Bernoulli equation as energy conservation along a streamline, and the strict conditions under which it may be used.",
      keywords:"steady unsteady uniform laminar turbulent transitional reynolds number inertial viscous forces streamline streamtube pathline streakline system control volume reynolds transport theorem conservation of mass continuity equation mass flow rate volumetric flow rate linear momentum equation newton second law bernoulli equation energy conservation pressure velocity elevation head total head stagnation inviscid incompressible frictionless along a streamline",
      related:[
        {type:"eq", label:"Reynolds number",             href:"equations.html#eq-reynolds"},
        {type:"eq", label:"Continuity",                  href:"equations.html#eq-continuity"},
        {type:"eq", label:"Momentum equation",           href:"equations.html#eq-momentum"},
        {type:"eq", label:"Bernoulli equation",          href:"equations.html#eq-bernoulli"},
        {type:"def",label:"Reynolds number",             href:"glossary.html#g-reynolds"},
        {type:"def",label:"Control volume",              href:"glossary.html#g-control-volume"},
        {type:"def",label:"Streamline",                  href:"glossary.html#g-streamline"}
      ]
    },
    {
      f:"week-04.html", week:4,
      t:"Flow Measurement &amp; the Extended Bernoulli Equation",
      summary:"Using Bernoulli to measure flow, and then repairing it. Venturi meters, orifice plates and Pitot tubes; the vena contracta and the three coefficients — contraction, velocity and discharge — that reconcile ideal theory with reality. Then the extended (energy) form of Bernoulli, adding friction head loss, pump work and turbine work, plus the kinetic-energy correction factor that fixes the velocity-head term for a non-uniform profile.",
      keywords:"flow measurement venturi meter orifice plate sharp edged nozzle pitot tube stagnation vena contracta contraction coefficient velocity coefficient discharge coefficient Cd Cc Cv ideal actual flow rate extended bernoulli energy equation head loss friction pump head turbine head shaft work power efficiency kinetic energy correction factor alpha velocity profile",
      related:[
        {type:"eq", label:"Orifice & venturi discharge", href:"equations.html#eq-orifice"},
        {type:"eq", label:"Discharge coefficient",       href:"equations.html#eq-discharge-coeff"},
        {type:"eq", label:"Extended Bernoulli",          href:"equations.html#eq-extended-bernoulli"},
        {type:"eq", label:"Pump & turbine power",        href:"equations.html#eq-pump-power"},
        {type:"def",label:"Vena contracta",              href:"glossary.html#g-vena-contracta"},
        {type:"def",label:"Discharge coefficient",       href:"glossary.html#g-discharge-coeff"}
      ]
    },
    {
      f:"week-05.html", week:5,
      t:"Viscosity &amp; the Navier–Stokes Equations",
      summary:"The differential governing equations. Newton's law of viscosity and the distinction between Newtonian and non-Newtonian fluids; the no-slip condition that every real flow obeys; then the differential continuity equation and the Navier–Stokes equations in compressible and incompressible form, term by term. Solving them exactly in the two classic cases where the geometry is simple enough — Couette flow between plates and Poiseuille flow in a pipe.",
      keywords:"newton law of viscosity shear stress velocity gradient newtonian non-newtonian shear thinning thickening bingham plastic no-slip condition differential continuity equation navier stokes equations compressible incompressible conservation of momentum inertia pressure gradient viscous term body force exact solutions couette flow poiseuille flow parabolic profile hagen poiseuille",
      related:[
        {type:"eq", label:"Newton's law of viscosity",   href:"equations.html#eq-newton-viscosity"},
        {type:"eq", label:"Differential continuity",     href:"equations.html#eq-diff-continuity"},
        {type:"eq", label:"Navier–Stokes equations",     href:"equations.html#eq-navier-stokes"},
        {type:"eq", label:"Hagen–Poiseuille",            href:"equations.html#eq-poiseuille"},
        {type:"def",label:"Newtonian fluid",             href:"glossary.html#g-newtonian"},
        {type:"def",label:"No-slip condition",           href:"glossary.html#g-no-slip"}
      ]
    },
    {
      f:"week-06.html", week:6,
      t:"Boundary Layers, Lift &amp; Drag",
      summary:"External flow around bodies. The boundary layer and how it grows, laminar then turbulent, and why a turbulent layer — despite more skin friction — resists separation better and can reduce total drag (the dimpled-golf-ball result). Resolving the surface force into drag along the flow and lift across it, splitting drag into friction and pressure (form) components, and the drag and lift coefficients used to make either dimensionless.",
      keywords:"external flow boundary layer thickness laminar turbulent transition separation point wake pressure drag form drag friction drag skin friction streamlining drag coefficient lift coefficient frontal area planform dynamic pressure terminal velocity golf ball dimples cylinder sphere aerofoil angle of attack stall",
      related:[
        {type:"eq", label:"Drag & lift force",           href:"equations.html#eq-drag-lift"},
        {type:"eq", label:"Dynamic pressure",            href:"equations.html#eq-dynamic-pressure"},
        {type:"def",label:"Boundary layer",              href:"glossary.html#g-boundary-layer"},
        {type:"def",label:"Flow separation",             href:"glossary.html#g-separation"},
        {type:"def",label:"Drag coefficient",            href:"glossary.html#g-drag-coeff"}
      ]
    },
    {
      f:"week-07.html", week:7,
      t:"Viscous Flow in Pipes",
      summary:"Internal flow, and where the energy actually goes. The entrance region and fully developed flow; laminar flow giving f = 64/Re exactly, and turbulent flow needing the Colebrook correlation or the Moody chart with its relative roughness. The Darcy–Weisbach equation for major (friction) losses along the pipe, and loss coefficients K for minor losses at bends, valves, entries and exits — with the caution that 'minor' losses often are not.",
      keywords:"internal flow pipe duct entrance region entry length fully developed velocity profile laminar turbulent critical reynolds 2300 darcy weisbach equation major loss friction factor darcy 64/Re colebrook correlation implicit moody chart relative roughness epsilon over D smooth rough minor losses local losses loss coefficient K bends elbows valves sudden expansion contraction entrance exit equivalent length",
      related:[
        {type:"eq", label:"Darcy–Weisbach",              href:"equations.html#eq-darcy-weisbach"},
        {type:"eq", label:"Friction factor",             href:"equations.html#eq-friction-factor"},
        {type:"eq", label:"Minor losses",                href:"equations.html#eq-minor-losses"},
        {type:"def",label:"Friction factor",             href:"glossary.html#g-friction-factor"},
        {type:"def",label:"Major & minor losses",        href:"glossary.html#g-losses"},
        {type:"def",label:"Fully developed flow",        href:"glossary.html#g-fully-developed"}
      ]
    },
    {
      f:"week-08.html", week:8,
      t:"Dimensional Analysis &amp; Similarity",
      summary:"Getting the most out of the fewest experiments. Dimensions versus units and the primary dimensions M, L, T, Θ; the Buckingham Pi theorem reducing k variables in r dimensions to k−r dimensionless groups, worked through its step-by-step recipe including the choice of repeating variables. Then similarity — geometric, kinematic and dynamic — and how matching the governing dimensionless group (Reynolds, Froude, Mach or Weber) lets a scale model predict the prototype.",
      keywords:"dimensional analysis dimensions units primary dimensions mass length time temperature MLT dimensional homogeneity buckingham pi theorem repeating variables non-repeating dimensionless groups reduce experiments similarity geometric kinematic dynamic similitude scale model prototype reynolds froude mach weber euler number matching",
      related:[
        {type:"eq", label:"Buckingham Pi theorem",       href:"equations.html#eq-buckingham"},
        {type:"eq", label:"Dimensionless groups",        href:"equations.html#eq-dimensionless-groups"},
        {type:"eq", label:"Dynamic similarity",          href:"equations.html#eq-similarity"},
        {type:"def",label:"Buckingham Pi theorem",       href:"glossary.html#g-buckingham"},
        {type:"def",label:"Dynamic similarity",          href:"glossary.html#g-similarity"}
      ]
    },
    {
      f:"week-09.html", week:9,
      t:"Pipe Systems 1",
      summary:"Assembling pipes into systems. The energy and hydraulic grade lines as a picture of where head is being spent, jumping at a pump and dropping at a turbine. Single-pipe systems with pumps and turbines solved from the extended Bernoulli equation, the three classic problem types (find head loss, find flow rate, find diameter), and pipes in series and in parallel — heads adding in one case, flows in the other.",
      keywords:"pipe system energy grade line EGL hydraulic grade line HGL total head elevation head reservoir pump jump turbine drop single pipe system three problem types find head loss flow rate diameter iteration series pipes parallel pipes head adds flow adds branched equivalent pipe pump performance curve system curve operating point efficiency",
      related:[
        {type:"eq", label:"Energy & hydraulic grade line",href:"equations.html#eq-egl-hgl"},
        {type:"eq", label:"Pipes in series & parallel",  href:"equations.html#eq-series-parallel"},
        {type:"def",label:"Energy grade line",           href:"glossary.html#g-egl"},
        {type:"def",label:"Operating point",             href:"glossary.html#g-operating-point"}
      ]
    },
    {
      f:"week-10.html", week:10,
      t:"Pipe Systems 2 — Networks",
      summary:"Larger networks, where the equations can no longer be solved directly. Branched systems meeting at a junction, the three-reservoir problem and how to guess the junction head, and pipe networks solved iteratively by the Hardy Cross method — assuming flows in each loop, computing the head-loss imbalance, and applying the correction until it converges. Extended to loops containing reservoirs and pumps.",
      keywords:"pipe network branched junction three reservoir problem junction head guess iteration hardy cross method loop continuity head loss balance correction factor delta Q convergence sign convention clockwise anticlockwise loops with reservoirs loops with pumps nodal analysis",
      related:[
        {type:"eq", label:"Hardy Cross correction",      href:"equations.html#eq-hardy-cross"},
        {type:"eq", label:"Network conditions",          href:"equations.html#eq-network"},
        {type:"def",label:"Hardy Cross method",          href:"glossary.html#g-hardy-cross"}
      ]
    },
    {
      f:"week-11.html", week:11,
      t:"Multiphase Flow",
      summary:"When more than one phase flows at once — gas and liquid in a pipeline, solids in a slurry, bubbles in a column. The quantities that describe it: quality, void fraction and liquid holdup, mass flux and the superficial velocities that let a two-phase mixture be plotted on a flow-regime map. The regimes themselves — bubble, slug, churn and annular in vertical pipes, with stratified and wavy added in horizontal ones — and why identifying the regime matters for pressure drop and stability.",
      keywords:"multiphase flow two-phase gas liquid solid slurry quality mass fraction void fraction liquid holdup mass flux superficial velocity actual velocity slip ratio homogeneous model flow regime map vertical bubble slug churn annular mist horizontal stratified wavy plug regime transition pressure drop fluidisation bubble column",
      related:[
        {type:"eq", label:"Quality & void fraction",     href:"equations.html#eq-quality-void"},
        {type:"eq", label:"Superficial velocity",        href:"equations.html#eq-superficial"},
        {type:"def",label:"Void fraction",               href:"glossary.html#g-void-fraction"},
        {type:"def",label:"Superficial velocity",        href:"glossary.html#g-superficial"},
        {type:"def",label:"Flow regime",                 href:"glossary.html#g-flow-regime"}
      ]
    },
    {
      f:"week-12.html", week:12,
      t:"Introduction to CFD",
      summary:"Solving the governing equations numerically when no analytical solution exists. What CFD is and when it is the right tool, the governing equations it discretises, and the finite volume method that turns them into an algebraic system over a mesh of control volumes. The workflow in ANSYS Fluent — geometry, mesh, physics setup, solve, post-process — and the discipline that makes the answer trustworthy: convergence, mesh independence and validation.",
      keywords:"computational fluid dynamics CFD governing equations discretisation finite volume method FVM control volume mesh grid cell node structured unstructured ansys fluent workflow geometry meshing boundary conditions solver iteration residual convergence mesh independence sensitivity validation verification post-processing contours vectors streamlines",
      related:[
        {type:"eq", label:"Finite volume discretisation",href:"equations.html#eq-fvm"},
        {type:"def",label:"Finite volume method",        href:"glossary.html#g-fvm"},
        {type:"def",label:"Mesh independence",           href:"glossary.html#g-mesh-independence"}
      ]
    }
  ],

  /* =========================================================
     EQUATIONS
     ========================================================= */
  equations:[
    /* ---- Fluid properties & statics ---- */
    {id:"eq-density", cat:"Fluid properties & statics", name:"Density, specific gravity & specific weight",
     latex:R`\rho = \frac{m}{V} \qquad SG = \frac{\rho}{\rho_{H_2O}} \qquad \gamma_s = \rho g`,
     desc:"Density is mass per unit volume. Specific gravity compares it to water at 4 °C and is dimensionless. Specific weight is the weight of a unit volume (N/m³).",
     vars:[{sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`m`,mean:"mass (kg)",href:"glossary.html#g-mass"},
           {sym:R`V`,mean:"volume (m³)",href:"glossary.html#g-volume"},
           {sym:R`SG`,mean:"specific gravity (dimensionless)",href:"glossary.html#g-density"},
           {sym:R`\rho_{H_2O}`,mean:"density of water, ≈1000 kg/m³",href:"glossary.html#g-density"},
           {sym:R`\gamma_s`,mean:"specific weight (N/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"}],
     links:[{label:"Week 1",href:"week-01.html"},{label:"Density",href:"glossary.html#g-density"}],
     keywords:"density specific gravity weight water reference intensive"},

    {id:"eq-viscosity", cat:"Fluid properties & statics", name:"Dynamic & kinematic viscosity",
     latex:R`\nu = \frac{\mu}{\rho}`,
     desc:"Viscosity measures resistance to flow, arising from internal friction between fluid layers moving relative to one another. Dynamic viscosity μ is in Pa·s; kinematic viscosity ν is in m²/s (1 stoke = 1 cm²/s). An inviscid flow is the idealisation μ = 0.",
     vars:[{sym:R`\nu`,mean:"kinematic viscosity (m²/s)",href:"glossary.html#g-viscosity"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"}],
     links:[{label:"Week 1",href:"week-01.html"},{label:"Viscosity",href:"glossary.html#g-viscosity"}],
     keywords:"viscosity dynamic kinematic stoke inviscid friction layers"},

    {id:"eq-hydrostatic", cat:"Fluid properties & statics", name:"Hydrostatic pressure & head",
     latex:R`P_1 = P_2 + \rho g h \qquad \Delta P = \rho g h \qquad h = \frac{\Delta P}{\rho g}`,
     desc:"From a force balance on a cylinder of stationary fluid. Pressure increases with depth because of the added weight above, and depends only on depth and density — not on the shape of the container. Expressed as a height of fluid, h is called the pressure head.",
     vars:[{sym:R`P_1,P_2`,mean:"pressures at the lower and upper points (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\Delta P`,mean:"pressure difference between them (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"fluid density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`h`,mean:"depth below the reference, or pressure head (m)",href:"glossary.html#g-head"}],
     links:[{label:"Week 1",href:"week-01.html"},{label:"Head",href:"glossary.html#g-head"}],
     keywords:"hydrostatic pressure depth head force balance container shape independent"},

    {id:"eq-gauge", cat:"Fluid properties & statics", name:"Gauge & absolute pressure",
     latex:R`P_{abs} = P_{atm} + P_{gauge} \qquad P_{gauge} = P - P_{atm}`,
     desc:"Pressure is nearly always quoted relative to a reference. Gauge pressure is measured relative to atmospheric; a negative gauge pressure is a vacuum. Absolute pressure is measured from a perfect vacuum, and is what the gas laws require.",
     vars:[{sym:R`P_{abs}`,mean:"absolute pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`P_{atm}`,mean:"atmospheric pressure, 101.325 kPa",href:"glossary.html#g-pressure"},
           {sym:R`P_{gauge}`,mean:"gauge pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`P`,mean:"the pressure being measured (Pa)",href:"glossary.html#g-pressure"}],
     links:[{label:"Week 1",href:"week-01.html"},{label:"Pressure",href:"glossary.html#g-pressure"}],
     keywords:"gauge absolute vacuum atmospheric reference bar atm psi torr"},

    {id:"eq-hydraulic-press", cat:"Fluid properties & statics", name:"Pascal's law & the hydraulic press",
     latex:R`P_1 = P_2 \quad\Rightarrow\quad \frac{F_1}{A_1} = \frac{F_2}{A_2} \quad\Rightarrow\quad F_2 = F_1\frac{A_2}{A_1}`,
     desc:"Pressure applied to a confined fluid at rest is transmitted undiminished in every direction. Because the pressure is common to both pistons, a small force on a small area produces a large force on a large one — the force is multiplied by the area ratio.",
     vars:[{sym:R`P_1,P_2`,mean:"pressures at the two pistons (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`F_1,F_2`,mean:"forces on the small and large pistons (N)",href:"glossary.html#g-force"},
           {sym:R`A_1,A_2`,mean:"areas of the small and large pistons (m²)",href:"glossary.html#g-area"}],
     links:[{label:"Week 1",href:"week-01.html"},{label:"Pascal's law",href:"glossary.html#g-pascal"}],
     keywords:"pascal law hydraulic press jack force multiplication area ratio confined"},

    {id:"eq-manometer", cat:"Fluid properties & statics", name:"Barometer & manometer",
     latex:R`P_{atm} = \rho g h \qquad P_A + \rho_1 g h_1 - \rho_{man} g h_2 = P_B`,
     desc:"A barometer measures atmospheric pressure as a column height against a vacuum — mercury is used because its high density keeps the column short and its vapour pressure is negligible. In a manometer, work along the tube adding ρgh going down and subtracting it going up.",
     vars:[{sym:R`P_{atm}`,mean:"atmospheric pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`P_A,P_B`,mean:"pressures at the two ends of the manometer (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho,\rho_1`,mean:"density of the working fluid (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`\rho_{man}`,mean:"density of the manometer fluid (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`h,h_1,h_2`,mean:"column heights (m)",href:"glossary.html#g-head"}],
     links:[{label:"Week 1",href:"week-01.html"}],
     keywords:"barometer manometer mercury u-tube column vapour pressure differential"},

    /* ---- Hydrostatic forces ---- */
    {id:"eq-hydrostatic-force", cat:"Hydrostatic forces & buoyancy", name:"Resultant force on a plane surface",
     latex:R`F_R = P_C A = \rho g h_C A = \rho g\,y_C\sin\theta\,A`,
     desc:"The pressure at the centroid is the average pressure over a plane surface, so the resultant force is simply that pressure times the area. It acts normal to the surface. For a horizontal surface the centre of pressure coincides with the centroid; for any inclined or vertical surface it does not.",
     vars:[{sym:R`F_R`,mean:"resultant hydrostatic force (N)",href:"glossary.html#g-force"},
           {sym:R`P_C`,mean:"pressure at the centroid (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"fluid density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`h_C`,mean:"vertical depth of the centroid (m)",href:"glossary.html#g-centroid"},
           {sym:R`y_C`,mean:"distance to the centroid along the surface (m)",href:"glossary.html#g-centroid"},
           {sym:R`\theta`,mean:"angle of the surface to the horizontal",href:"glossary.html#g-angle"},
           {sym:R`A`,mean:"area of the submerged surface (m²)",href:"glossary.html#g-area"}],
     links:[{label:"Week 2",href:"week-02.html"},{label:"Centre of pressure",href:"glossary.html#g-centre-pressure"}],
     keywords:"resultant force plane submerged surface centroid average pressure gate inclined"},

    {id:"eq-centre-pressure", cat:"Hydrostatic forces & buoyancy", name:"Centre of pressure",
     latex:R`y_R = y_C + \frac{I_{xx,C}}{y_C A}`,
     desc:"Taking moments of the pressure distribution about the free surface locates the line of action. The centre of pressure always lies BELOW the centroid, by an amount that shrinks as the surface is submerged deeper — because the pressure gradient matters less relative to the mean.",
     vars:[{sym:R`y_R`,mean:"distance to the centre of pressure (m)",href:"glossary.html#g-centre-pressure"},
           {sym:R`y_C`,mean:"distance to the centroid (m)",href:"glossary.html#g-centroid"},
           {sym:R`I_{xx,C}`,mean:"second moment of area about the centroidal axis (m⁴)",href:"glossary.html#g-second-moment"},
           {sym:R`A`,mean:"area of the surface (m²)",href:"glossary.html#g-area"}],
     links:[{label:"Week 2",href:"week-02.html"},{label:"Second moment of area",href:"glossary.html#g-second-moment"}],
     keywords:"centre of pressure moment parallel axis below centroid line of action"},

    {id:"eq-buoyancy", cat:"Hydrostatic forces & buoyancy", name:"Buoyant force (Archimedes)",
     latex:R`F_B = \rho g V_{disp} \qquad \text{floating: } F_B = W`,
     desc:"Archimedes' principle: the upward force on an immersed body equals the weight of the fluid it displaces, acting through the centroid of the displaced volume (the centre of buoyancy). A floating body displaces exactly its own weight. Stability depends on the metacentre lying above the centre of gravity.",
     vars:[{sym:R`F_B`,mean:"buoyant force (N)",href:"glossary.html#g-buoyancy"},
           {sym:R`\rho`,mean:"density of the fluid (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`V_{disp}`,mean:"displaced volume (m³)",href:"glossary.html#g-volume"},
           {sym:R`W`,mean:"weight of the body (N)",href:"glossary.html#g-force"}],
     links:[{label:"Week 2",href:"week-02.html"},{label:"Metacentre",href:"glossary.html#g-metacentre"}],
     keywords:"buoyancy archimedes displaced volume floating submerged centre of buoyancy stability"},

    /* ---- Continuity & Bernoulli ---- */
    {id:"eq-reynolds", cat:"Continuity, momentum & Bernoulli", name:"Reynolds number",
     latex:R`Re = \frac{\rho u D}{\mu} = \frac{u D}{\nu}`,
     desc:"The ratio of inertial to viscous forces, and the single number that decides flow character. Laminar flow is viscosity-dominated; turbulent flow is inertia-dominated. In a pipe the transition sits near Re ≈ 2300.",
     vars:[{sym:R`Re`,mean:"Reynolds number (dimensionless)",href:"glossary.html#g-reynolds"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`u`,mean:"characteristic velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`D`,mean:"characteristic length, e.g. pipe diameter (m)",href:"glossary.html#g-diameter"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`\nu`,mean:"kinematic viscosity (m²/s)",href:"glossary.html#g-viscosity"}],
     links:[{label:"Week 3",href:"week-03.html"},{label:"Week 7",href:"week-07.html"},{label:"Reynolds number",href:"glossary.html#g-reynolds"}],
     keywords:"reynolds number laminar turbulent transition inertial viscous 2300 dimensionless"},

    {id:"eq-continuity", cat:"Continuity, momentum & Bernoulli", name:"Conservation of mass (continuity)",
     latex:R`\dot m = \rho A u = \text{const} \qquad \rho_1 A_1 u_1 = \rho_2 A_2 u_2 \qquad A_1u_1 = A_2u_2`,
     desc:"For steady flow through a streamtube, mass in equals mass out. If the fluid is also incompressible the density cancels, leaving the volumetric flow rate constant — which is why a narrowing pipe speeds the flow up.",
     vars:[{sym:R`\dot m`,mean:"mass flow rate (kg/s)",href:"glossary.html#g-mass-flow"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`A`,mean:"cross-sectional area (m²)",href:"glossary.html#g-area"},
           {sym:R`u`,mean:"velocity normal to the area (m/s)",href:"glossary.html#g-velocity"}],
     links:[{label:"Week 3",href:"week-03.html"},{label:"Control volume",href:"glossary.html#g-control-volume"}],
     keywords:"continuity conservation of mass steady streamtube incompressible volumetric flow rate"},

    {id:"eq-momentum", cat:"Continuity, momentum & Bernoulli", name:"Linear momentum equation",
     latex:R`\sum \vec F = \dot m\,(\vec u_{out} - \vec u_{in})`,
     desc:"Newton's second law for a control volume at steady state: the net force on the fluid equals the rate at which momentum leaves minus the rate at which it enters. It is a VECTOR equation — resolve into components — and it is what gives the force on a bend, a nozzle or a turbine blade.",
     vars:[{sym:R`\sum \vec F`,mean:"net force on the control volume (N)",href:"glossary.html#g-force"},
           {sym:R`\dot m`,mean:"mass flow rate (kg/s)",href:"glossary.html#g-mass-flow"},
           {sym:R`\vec u_{in},\vec u_{out}`,mean:"inlet and outlet velocities (m/s)",href:"glossary.html#g-velocity"}],
     links:[{label:"Week 3",href:"week-03.html"}],
     keywords:"momentum equation newton second law control volume force bend nozzle vector components"},

    {id:"eq-bernoulli", cat:"Continuity, momentum & Bernoulli", name:"Bernoulli equation",
     latex:R`\frac{P}{\rho g} + \frac{u^2}{2g} + z = \text{const} \qquad P + \tfrac12\rho u^2 + \rho g z = \text{const}`,
     desc:"Energy conservation along a streamline: pressure head plus velocity head plus elevation head is constant. Valid only for steady, incompressible, inviscid (frictionless) flow with no shaft work and no heat transfer — check every one of those before using it.",
     vars:[{sym:R`P`,mean:"static pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`u`,mean:"flow velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`z`,mean:"elevation above datum (m)",href:"glossary.html#g-elevation"}],
     links:[{label:"Week 3",href:"week-03.html"},{label:"Week 4",href:"week-04.html"},{label:"Head",href:"glossary.html#g-head"}],
     keywords:"bernoulli equation energy streamline pressure velocity elevation head total constant inviscid"},

    /* ---- Flow measurement ---- */
    {id:"eq-orifice", cat:"Flow measurement & energy", name:"Orifice & venturi flow rate",
     latex:R`Q_{actual} = C_d A_o\sqrt{2gh} \qquad Q_{actual} = C_d A_o\sqrt{\frac{2(P_1-P_2)}{\rho\,[1-(A_o/A_1)^2]}}`,
     desc:"Bernoulli plus continuity gives the ideal discharge; the coefficient corrects it. The first form is for free discharge under a head h, the second for a meter between two pressure tappings, where the area-ratio term accounts for the approach velocity.",
     vars:[{sym:R`Q_{actual}`,mean:"actual volumetric flow rate (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`C_d`,mean:"discharge coefficient",href:"glossary.html#g-discharge-coeff"},
           {sym:R`A_o`,mean:"orifice or throat area (m²)",href:"glossary.html#g-area"},
           {sym:R`A_1`,mean:"upstream pipe area (m²)",href:"glossary.html#g-area"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`h`,mean:"driving head (m)",href:"glossary.html#g-head"},
           {sym:R`P_1,P_2`,mean:"upstream and throat pressures (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"}],
     links:[{label:"Week 4",href:"week-04.html"},{label:"Vena contracta",href:"glossary.html#g-vena-contracta"}],
     keywords:"orifice venturi flow meter discharge measurement tappings area ratio"},

    {id:"eq-discharge-coeff", cat:"Flow measurement & energy", name:"Contraction, velocity & discharge coefficients",
     latex:R`C_c = \frac{A_2}{A_o} \qquad C_v = \frac{u_{actual}}{u_{ideal}} \qquad C_d = C_c C_v < 1`,
     desc:"Three separate corrections. The jet contracts past the opening to the vena contracta (Cc), friction reduces the velocity below the ideal (Cv), and their product is the discharge coefficient. For a sharp-edged orifice Cv ≈ 0.97–0.99, Cc ≈ 0.61–0.66 and so Cd ≈ 0.6–0.65.",
     vars:[{sym:R`C_c`,mean:"contraction coefficient",href:"glossary.html#g-discharge-coeff"},
           {sym:R`C_v`,mean:"velocity coefficient",href:"glossary.html#g-discharge-coeff"},
           {sym:R`C_d`,mean:"discharge coefficient",href:"glossary.html#g-discharge-coeff"},
           {sym:R`A_2`,mean:"area at the vena contracta (m²)",href:"glossary.html#g-vena-contracta"},
           {sym:R`A_o`,mean:"geometric orifice area (m²)",href:"glossary.html#g-area"},
           {sym:R`u_{actual},u_{ideal}`,mean:"actual and ideal jet velocity (m/s)",href:"glossary.html#g-velocity"}],
     links:[{label:"Week 4",href:"week-04.html"},{label:"Discharge coefficient",href:"glossary.html#g-discharge-coeff"}],
     keywords:"contraction velocity discharge coefficient vena contracta sharp edged orifice typical values"},

    {id:"eq-extended-bernoulli", cat:"Flow measurement & energy", name:"Extended (energy) Bernoulli equation",
     latex:R`\frac{P_1}{\rho g} + \frac{\alpha_1 u_1^2}{2g} + z_1 + h_{pump} = \frac{P_2}{\rho g} + \frac{\alpha_2 u_2^2}{2g} + z_2 + h_{turbine} + h_{loss}`,
     desc:"Bernoulli repaired for reality. Friction always removes head (h_loss is positive), a pump adds head and a turbine extracts it. The kinetic-energy correction factor α accounts for the velocity profile not being uniform — α ≈ 2 for laminar pipe flow and ≈ 1.05 for turbulent.",
     vars:[{sym:R`P_1,P_2`,mean:"pressures at the two sections (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`\alpha_1,\alpha_2`,mean:"kinetic-energy correction factors",href:"glossary.html#g-ke-correction"},
           {sym:R`u_1,u_2`,mean:"mean velocities (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`z_1,z_2`,mean:"elevations (m)",href:"glossary.html#g-elevation"},
           {sym:R`h_{pump}`,mean:"head added by a pump (m)",href:"glossary.html#g-head"},
           {sym:R`h_{turbine}`,mean:"head extracted by a turbine (m)",href:"glossary.html#g-head"},
           {sym:R`h_{loss}`,mean:"head lost to friction (m)",href:"glossary.html#g-losses"}],
     links:[{label:"Week 4",href:"week-04.html"},{label:"Week 9",href:"week-09.html"}],
     keywords:"extended bernoulli energy equation head loss pump turbine kinetic energy correction alpha"},

    {id:"eq-pump-power", cat:"Flow measurement & energy", name:"Pump & turbine power",
     latex:R`\dot W_{pump} = \frac{\rho g Q h_{pump}}{\eta_{pump}} \qquad \dot W_{turbine} = \eta_{turbine}\,\rho g Q h_{turbine}`,
     desc:"The hydraulic power exchanged with the fluid is ρgQh. A pump needs MORE shaft power than that because of its efficiency; a turbine delivers LESS. Getting the efficiency the right way up is the usual slip.",
     vars:[{sym:R`\dot W_{pump}`,mean:"shaft power required by the pump (W)",href:"glossary.html#g-power"},
           {sym:R`\dot W_{turbine}`,mean:"shaft power delivered by the turbine (W)",href:"glossary.html#g-power"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`Q`,mean:"volumetric flow rate (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`h_{pump},h_{turbine}`,mean:"head added or extracted (m)",href:"glossary.html#g-head"},
           {sym:R`\eta_{pump},\eta_{turbine}`,mean:"pump and turbine efficiency",href:"glossary.html#g-efficiency"}],
     links:[{label:"Week 4",href:"week-04.html"},{label:"Week 9",href:"week-09.html"}],
     keywords:"pump turbine power hydraulic shaft efficiency rho g Q h"},

    /* ---- Navier-Stokes ---- */
    {id:"eq-newton-viscosity", cat:"Viscous flow & Navier–Stokes", name:"Newton's law of viscosity",
     latex:R`\tau = \mu\frac{du}{dy}`,
     desc:"Shear stress is proportional to the velocity gradient, with dynamic viscosity as the constant. A fluid obeying this is Newtonian (water, air, most oils). Non-Newtonian fluids have a viscosity that changes with shear rate — shear-thinning, shear-thickening or Bingham plastic.",
     vars:[{sym:R`\tau`,mean:"shear stress (Pa)",href:"glossary.html#g-shear-stress"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`u`,mean:"velocity parallel to the surface (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`y`,mean:"distance normal to the surface (m)",href:"glossary.html#g-coordinate"}],
     links:[{label:"Week 5",href:"week-05.html"},{label:"Newtonian fluid",href:"glossary.html#g-newtonian"}],
     keywords:"newton law viscosity shear stress velocity gradient newtonian non-newtonian bingham"},

    {id:"eq-diff-continuity", cat:"Viscous flow & Navier–Stokes", name:"Differential continuity equation",
     latex:R`\frac{\partial\rho}{\partial t} + \nabla\!\cdot\!(\rho\vec u) = 0 \qquad\xrightarrow{\ \text{incompressible}\ }\qquad \nabla\!\cdot\!\vec u = 0`,
     desc:"Conservation of mass written at a point rather than over a control volume. For an incompressible fluid it reduces to the statement that the velocity field is divergence-free — what flows into an element must flow out.",
     vars:[{sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`t`,mean:"time (s)",href:"glossary.html#g-time"},
           {sym:R`\vec u`,mean:"velocity vector (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`\nabla\!\cdot`,mean:"divergence operator",href:"glossary.html#g-navier-stokes"}],
     links:[{label:"Week 5",href:"week-05.html"},{label:"Week 12",href:"week-12.html"}],
     keywords:"differential continuity divergence incompressible point form conservation of mass"},

    {id:"eq-navier-stokes", cat:"Viscous flow & Navier–Stokes", name:"Navier–Stokes equations (incompressible)",
     latex:R`\rho\!\left(\frac{\partial \vec u}{\partial t} + \vec u\!\cdot\!\nabla\vec u\right) = -\nabla P + \mu\nabla^2\vec u + \rho\vec g`,
     desc:"Newton's second law for a fluid particle. Left: unsteady plus convective acceleration. Right: the pressure gradient, the viscous term, and gravity. There is no general analytical solution — which is exactly why CFD exists — but simple geometries can be solved exactly.",
     vars:[{sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`\vec u`,mean:"velocity vector (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`t`,mean:"time (s)",href:"glossary.html#g-time"},
           {sym:R`P`,mean:"pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`\vec g`,mean:"gravitational acceleration vector (m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`\nabla,\nabla^2`,mean:"gradient and Laplacian operators",href:"glossary.html#g-navier-stokes"}],
     links:[{label:"Week 5",href:"week-05.html"},{label:"Week 12",href:"week-12.html"},{label:"Navier–Stokes",href:"glossary.html#g-navier-stokes"}],
     keywords:"navier stokes momentum differential convective acceleration pressure gradient viscous body force"},

    {id:"eq-poiseuille", cat:"Viscous flow & Navier–Stokes", name:"Hagen–Poiseuille (laminar pipe flow)",
     latex:R`u(r) = \frac{\Delta P}{4\mu L}\big(R^2-r^2\big) \qquad Q = \frac{\pi R^4 \Delta P}{8\mu L} \qquad u_{max} = 2\bar u`,
     desc:"The exact Navier–Stokes solution for steady laminar flow in a circular pipe. The profile is parabolic, the peak velocity is twice the mean, and the flow rate goes as the FOURTH power of radius — halve the pipe and you cut the flow to a sixteenth.",
     vars:[{sym:R`u(r)`,mean:"velocity at radius r (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`\bar u`,mean:"mean velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`u_{max}`,mean:"centreline velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`\Delta P`,mean:"pressure drop over the length (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`L`,mean:"pipe length (m)",href:"glossary.html#g-length"},
           {sym:R`R`,mean:"pipe radius (m)",href:"glossary.html#g-radius"},
           {sym:R`r`,mean:"radial position (m)",href:"glossary.html#g-radius"},
           {sym:R`Q`,mean:"volumetric flow rate (m³/s)",href:"glossary.html#g-flow-rate"}],
     links:[{label:"Week 5",href:"week-05.html"},{label:"Week 7",href:"week-07.html"}],
     keywords:"hagen poiseuille laminar pipe parabolic profile fourth power exact solution couette"},

    /* ---- Boundary layers, lift & drag ---- */
    {id:"eq-dynamic-pressure", cat:"Boundary layers, lift & drag", name:"Dynamic pressure",
     latex:R`q = \tfrac12\rho u^2`,
     desc:"The kinetic energy per unit volume of the oncoming stream. It is the natural scale for any flow-induced force, which is why every drag and lift coefficient is defined by dividing by it.",
     vars:[{sym:R`q`,mean:"dynamic pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"fluid density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`u`,mean:"free-stream velocity (m/s)",href:"glossary.html#g-velocity"}],
     links:[{label:"Week 6",href:"week-06.html"}],
     keywords:"dynamic pressure kinetic energy per volume scale stagnation"},

    {id:"eq-drag-lift", cat:"Boundary layers, lift & drag", name:"Drag & lift force",
     latex:R`F_D = C_D\,\tfrac12\rho u^2 A \qquad F_L = C_L\,\tfrac12\rho u^2 A`,
     desc:"The surface force on a body resolved along the flow (drag) and across it (lift), each written as a coefficient times dynamic pressure times a reference area. Drag combines skin friction and pressure (form) drag; which dominates depends on the shape and on whether the boundary layer separates.",
     vars:[{sym:R`F_D`,mean:"drag force, along the flow (N)",href:"glossary.html#g-force"},
           {sym:R`F_L`,mean:"lift force, across the flow (N)",href:"glossary.html#g-force"},
           {sym:R`C_D`,mean:"drag coefficient",href:"glossary.html#g-drag-coeff"},
           {sym:R`C_L`,mean:"lift coefficient",href:"glossary.html#g-drag-coeff"},
           {sym:R`\rho`,mean:"fluid density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`u`,mean:"free-stream velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`A`,mean:"reference area — frontal for drag, planform for lift (m²)",href:"glossary.html#g-area"}],
     links:[{label:"Week 6",href:"week-06.html"},{label:"Drag coefficient",href:"glossary.html#g-drag-coeff"}],
     keywords:"drag lift coefficient frontal planform area friction pressure form separation streamlining"},

    /* ---- Pipe flow ---- */
    {id:"eq-darcy-weisbach", cat:"Viscous flow in pipes", name:"Darcy–Weisbach equation (major loss)",
     latex:R`h_f = f\,\frac{L}{D}\,\frac{u^2}{2g} \qquad \Delta P = f\,\frac{L}{D}\,\frac{\rho u^2}{2}`,
     desc:"The head lost to wall friction along a run of pipe — the 'major' loss. It grows linearly with length, inversely with diameter, and with the SQUARE of velocity, which is why oversizing a pipe pays off so quickly.",
     vars:[{sym:R`h_f`,mean:"friction head loss (m)",href:"glossary.html#g-losses"},
           {sym:R`\Delta P`,mean:"pressure drop (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`f`,mean:"Darcy friction factor",href:"glossary.html#g-friction-factor"},
           {sym:R`L`,mean:"pipe length (m)",href:"glossary.html#g-length"},
           {sym:R`D`,mean:"pipe diameter (m)",href:"glossary.html#g-diameter"},
           {sym:R`u`,mean:"mean velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"}],
     links:[{label:"Week 7",href:"week-07.html"},{label:"Major & minor losses",href:"glossary.html#g-losses"}],
     keywords:"darcy weisbach major loss friction head pressure drop length diameter velocity squared"},

    {id:"eq-friction-factor", cat:"Viscous flow in pipes", name:"Friction factor — laminar & turbulent",
     latex:R`f = \frac{64}{Re}\ \ (\text{laminar}) \qquad \frac{1}{\sqrt f} = -2\log_{10}\!\left(\frac{\varepsilon/D}{3.7} + \frac{2.51}{Re\sqrt f}\right)\ \ (\text{turbulent})`,
     desc:"In laminar flow the friction factor depends on Reynolds number alone and roughness is irrelevant. In turbulent flow it depends on both Re and the relative roughness, via the implicit Colebrook correlation — solved by iteration, or read straight off the Moody chart.",
     vars:[{sym:R`f`,mean:"Darcy friction factor",href:"glossary.html#g-friction-factor"},
           {sym:R`Re`,mean:"Reynolds number",href:"glossary.html#g-reynolds"},
           {sym:R`\varepsilon`,mean:"absolute wall roughness (m)",href:"glossary.html#g-roughness"},
           {sym:R`\varepsilon/D`,mean:"relative roughness",href:"glossary.html#g-roughness"},
           {sym:R`D`,mean:"pipe diameter (m)",href:"glossary.html#g-diameter"}],
     links:[{label:"Week 7",href:"week-07.html"},{label:"Friction factor",href:"glossary.html#g-friction-factor"}],
     keywords:"friction factor laminar 64 over Re colebrook implicit iteration moody chart relative roughness"},

    {id:"eq-minor-losses", cat:"Viscous flow in pipes", name:"Minor (local) losses",
     latex:R`h_L = K\,\frac{u^2}{2g} \qquad L_{eq} = \frac{K D}{f}`,
     desc:"Losses at bends, valves, entries, exits and sudden area changes, each given a loss coefficient K from tables. They can equivalently be expressed as a length of straight pipe producing the same loss. In a short pipe with many fittings, the 'minor' losses can easily exceed the major ones.",
     vars:[{sym:R`h_L`,mean:"minor head loss (m)",href:"glossary.html#g-losses"},
           {sym:R`K`,mean:"loss coefficient for the fitting",href:"glossary.html#g-losses"},
           {sym:R`u`,mean:"mean velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`L_{eq}`,mean:"equivalent length of straight pipe (m)",href:"glossary.html#g-length"},
           {sym:R`D`,mean:"pipe diameter (m)",href:"glossary.html#g-diameter"},
           {sym:R`f`,mean:"Darcy friction factor",href:"glossary.html#g-friction-factor"}],
     links:[{label:"Week 7",href:"week-07.html"}],
     keywords:"minor local losses fittings bends valves entrance exit expansion contraction K equivalent length"},

    /* ---- Dimensional analysis ---- */
    {id:"eq-buckingham", cat:"Dimensional analysis & similarity", name:"Buckingham Pi theorem",
     latex:R`\Pi_1 = \phi(\Pi_2,\dots,\Pi_{k-r}) \qquad \text{number of groups} = k - r`,
     desc:"A relationship among k dimensional variables in r primary dimensions can be rewritten as a relationship among just k−r dimensionless groups. Choose r repeating variables that between them cover all the dimensions, never including the dependent variable, then combine each remaining variable with them in turn.",
     vars:[{sym:R`\Pi_i`,mean:"the dimensionless groups",href:"glossary.html#g-buckingham"},
           {sym:R`k`,mean:"number of dimensional variables",href:"glossary.html#g-buckingham"},
           {sym:R`r`,mean:"number of primary dimensions involved",href:"glossary.html#g-buckingham"},
           {sym:R`\phi`,mean:"some unknown function determined by experiment",href:"glossary.html#g-buckingham"}],
     links:[{label:"Week 8",href:"week-08.html"},{label:"Buckingham Pi",href:"glossary.html#g-buckingham"}],
     keywords:"buckingham pi theorem dimensionless groups repeating variables reduce experiments primary dimensions"},

    {id:"eq-dimensionless-groups", cat:"Dimensional analysis & similarity", name:"The common dimensionless groups",
     latex:R`Re = \frac{\rho u L}{\mu} \qquad Fr = \frac{u}{\sqrt{gL}} \qquad Ma = \frac{u}{c} \qquad We = \frac{\rho u^2 L}{\sigma}`,
     desc:"Each compares inertia against a different competing effect: viscosity (Reynolds), gravity (Froude), compressibility (Mach) and surface tension (Weber). Which one governs tells you which must be matched between a model and its prototype.",
     vars:[{sym:R`Re`,mean:"Reynolds number — inertia vs viscosity",href:"glossary.html#g-reynolds"},
           {sym:R`Fr`,mean:"Froude number — inertia vs gravity",href:"glossary.html#g-similarity"},
           {sym:R`Ma`,mean:"Mach number — speed vs speed of sound",href:"glossary.html#g-similarity"},
           {sym:R`We`,mean:"Weber number — inertia vs surface tension",href:"glossary.html#g-similarity"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`u`,mean:"characteristic velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`L`,mean:"characteristic length (m)",href:"glossary.html#g-length"},
           {sym:R`\mu`,mean:"dynamic viscosity (Pa·s)",href:"glossary.html#g-viscosity"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`c`,mean:"speed of sound (m/s)",href:"glossary.html#g-similarity"},
           {sym:R`\sigma`,mean:"surface tension (N/m)",href:"glossary.html#g-similarity"}],
     links:[{label:"Week 8",href:"week-08.html"}],
     keywords:"reynolds froude mach weber euler dimensionless groups inertia viscosity gravity compressibility surface tension"},

    {id:"eq-similarity", cat:"Dimensional analysis & similarity", name:"Dynamic similarity",
     latex:R`\Pi_{i,\text{model}} = \Pi_{i,\text{prototype}} \quad\Rightarrow\quad \frac{\rho_m u_m L_m}{\mu_m} = \frac{\rho_p u_p L_p}{\mu_p}`,
     desc:"Two flows are dynamically similar when every governing dimensionless group matches — which requires geometric similarity (same shape) and kinematic similarity (same velocity-field shape) first. Matching the group then lets a measurement on the model be scaled to the prototype.",
     vars:[{sym:R`\Pi_i`,mean:"the governing dimensionless group",href:"glossary.html#g-similarity"},
           {sym:R`\rho_m,\rho_p`,mean:"model and prototype density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`u_m,u_p`,mean:"model and prototype velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`L_m,L_p`,mean:"model and prototype length (m)",href:"glossary.html#g-length"},
           {sym:R`\mu_m,\mu_p`,mean:"model and prototype viscosity (Pa·s)",href:"glossary.html#g-viscosity"}],
     links:[{label:"Week 8",href:"week-08.html"},{label:"Similarity",href:"glossary.html#g-similarity"}],
     keywords:"dynamic similarity geometric kinematic model prototype scale towing tank wind tunnel matching"},

    /* ---- Pipe systems ---- */
    {id:"eq-egl-hgl", cat:"Pipe systems", name:"Energy & hydraulic grade lines",
     latex:R`EGL = \frac{P}{\rho g} + \frac{u^2}{2g} + z \qquad HGL = \frac{P}{\rho g} + z = EGL - \frac{u^2}{2g}`,
     desc:"A picture of where head is going along a system. The EGL is the total head and always falls in the direction of flow except across a pump; the HGL sits one velocity head below it. The HGL dropping below the pipe means sub-atmospheric pressure — a cavitation risk.",
     vars:[{sym:R`EGL`,mean:"energy grade line — total head (m)",href:"glossary.html#g-egl"},
           {sym:R`HGL`,mean:"hydraulic grade line — piezometric head (m)",href:"glossary.html#g-egl"},
           {sym:R`P`,mean:"pressure (Pa)",href:"glossary.html#g-pressure"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`g`,mean:"gravitational acceleration (9.81 m/s²)",href:"glossary.html#g-gravity"},
           {sym:R`u`,mean:"mean velocity (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`z`,mean:"elevation above datum (m)",href:"glossary.html#g-elevation"}],
     links:[{label:"Week 9",href:"week-09.html"},{label:"Energy grade line",href:"glossary.html#g-egl"}],
     keywords:"energy grade line hydraulic grade line total piezometric head pump jump turbine drop cavitation"},

    {id:"eq-series-parallel", cat:"Pipe systems", name:"Pipes in series & parallel",
     latex:R`\text{Series: } Q = Q_1 = Q_2,\ \ h_L = h_{L1} + h_{L2} \qquad \text{Parallel: } h_L = h_{L1} = h_{L2},\ \ Q = Q_1 + Q_2`,
     desc:"In series the same flow passes through each pipe and the losses add. In parallel each branch sees the same head difference between the common junctions, and the flows add — so the flow divides itself so as to equalise the head loss.",
     vars:[{sym:R`Q`,mean:"total volumetric flow rate (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`Q_1,Q_2`,mean:"flow in each pipe (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`h_L`,mean:"total head loss (m)",href:"glossary.html#g-losses"},
           {sym:R`h_{L1},h_{L2}`,mean:"head loss in each pipe (m)",href:"glossary.html#g-losses"}],
     links:[{label:"Week 9",href:"week-09.html"},{label:"Week 10",href:"week-10.html"}],
     keywords:"series parallel pipes head loss adds flow adds junction equivalent branch"},

    {id:"eq-network", cat:"Pipe systems", name:"Network conditions",
     latex:R`\sum_{\text{node}} Q = 0 \qquad \sum_{\text{loop}} h_L = 0`,
     desc:"The two rules every pipe network must satisfy — continuity at each junction, and zero net head change around any closed loop. They are the direct analogue of Kirchhoff's current and voltage laws, and they are what the Hardy Cross iteration enforces.",
     vars:[{sym:R`Q`,mean:"flow into or out of a node (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`h_L`,mean:"head loss around a loop (m)",href:"glossary.html#g-losses"}],
     links:[{label:"Week 10",href:"week-10.html"},{label:"Hardy Cross",href:"glossary.html#g-hardy-cross"}],
     keywords:"network node continuity loop head balance kirchhoff analogue junction"},

    {id:"eq-hardy-cross", cat:"Pipe systems", name:"Hardy Cross correction",
     latex:R`\Delta Q = -\frac{\sum h_L}{n\sum |h_L / Q|} \qquad (n = 2 \text{ for Darcy–Weisbach})`,
     desc:"Guess a flow in each loop satisfying continuity, compute the head-loss imbalance, and apply this correction to every pipe in the loop. Repeat until the imbalance is acceptably small. The sign convention (clockwise positive) must be kept consistent or it will not converge.",
     vars:[{sym:R`\Delta Q`,mean:"flow correction applied to the loop (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`h_L`,mean:"head loss in each pipe of the loop (m)",href:"glossary.html#g-losses"},
           {sym:R`Q`,mean:"assumed flow in each pipe (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`n`,mean:"exponent of Q in the head-loss law",href:"glossary.html#g-hardy-cross"}],
     links:[{label:"Week 10",href:"week-10.html"},{label:"Hardy Cross",href:"glossary.html#g-hardy-cross"}],
     keywords:"hardy cross iteration loop correction convergence sign convention clockwise network"},

    /* ---- Multiphase ---- */
    {id:"eq-quality-void", cat:"Multiphase flow", name:"Quality, void fraction & holdup",
     latex:R`x = \frac{\dot m_G}{\dot m_G + \dot m_L} \qquad \alpha = \frac{A_G}{A} \qquad H_L = 1 - \alpha`,
     desc:"Quality is the GAS mass fraction; void fraction is the fraction of the pipe cross-section occupied by gas; liquid holdup is what is left. Because the phases travel at different speeds (slip), the void fraction is not simply the volumetric flow fraction.",
     vars:[{sym:R`x`,mean:"quality — gas mass fraction",href:"glossary.html#g-void-fraction"},
           {sym:R`\dot m_G,\dot m_L`,mean:"gas and liquid mass flow rates (kg/s)",href:"glossary.html#g-mass-flow"},
           {sym:R`\alpha`,mean:"void fraction — gas area fraction",href:"glossary.html#g-void-fraction"},
           {sym:R`A_G`,mean:"cross-section occupied by gas (m²)",href:"glossary.html#g-area"},
           {sym:R`A`,mean:"total pipe cross-section (m²)",href:"glossary.html#g-area"},
           {sym:R`H_L`,mean:"liquid holdup",href:"glossary.html#g-void-fraction"}],
     links:[{label:"Week 11",href:"week-11.html"},{label:"Void fraction",href:"glossary.html#g-void-fraction"}],
     keywords:"quality void fraction liquid holdup gas mass fraction slip area fraction two-phase"},

    {id:"eq-superficial", cat:"Multiphase flow", name:"Superficial velocity",
     latex:R`u_{SG} = \frac{Q_G}{A} \qquad u_{SL} = \frac{Q_L}{A} \qquad u_G = \frac{u_{SG}}{\alpha},\quad u_L = \frac{u_{SL}}{1-\alpha}`,
     desc:"The superficial velocity is the speed a phase WOULD have if it occupied the whole pipe alone at its actual flow rate. It is a convenient bookkeeping quantity — and the axes of the flow-regime maps — but the true phase velocity is higher, since each phase only has part of the area.",
     vars:[{sym:R`u_{SG},u_{SL}`,mean:"superficial gas and liquid velocities (m/s)",href:"glossary.html#g-superficial"},
           {sym:R`Q_G,Q_L`,mean:"gas and liquid volumetric flow rates (m³/s)",href:"glossary.html#g-flow-rate"},
           {sym:R`A`,mean:"pipe cross-sectional area (m²)",href:"glossary.html#g-area"},
           {sym:R`u_G,u_L`,mean:"actual (in-situ) phase velocities (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`\alpha`,mean:"void fraction",href:"glossary.html#g-void-fraction"}],
     links:[{label:"Week 11",href:"week-11.html"},{label:"Superficial velocity",href:"glossary.html#g-superficial"}],
     keywords:"superficial velocity flux flow regime map actual in-situ phase velocity slip"},

    /* ---- CFD ---- */
    {id:"eq-fvm", cat:"Computational fluid dynamics", name:"Finite volume discretisation",
     latex:R`\frac{\partial}{\partial t}\!\int_V \rho\phi\,dV + \oint_S \rho\phi\,\vec u\!\cdot\!d\vec S = \oint_S \Gamma\nabla\phi\!\cdot\!d\vec S + \int_V S_\phi\,dV`,
     desc:"The governing equations integrated over each control volume of the mesh: accumulation plus net convection out equals net diffusion in plus generation. Setting φ = 1 gives continuity, φ = u gives momentum. Each cell yields one algebraic equation, and the system is solved iteratively.",
     vars:[{sym:R`\phi`,mean:"the transported quantity (1, velocity, energy …)",href:"glossary.html#g-fvm"},
           {sym:R`\rho`,mean:"density (kg/m³)",href:"glossary.html#g-density"},
           {sym:R`t`,mean:"time (s)",href:"glossary.html#g-time"},
           {sym:R`V`,mean:"the control volume (cell)",href:"glossary.html#g-fvm"},
           {sym:R`S`,mean:"the cell's bounding surface",href:"glossary.html#g-fvm"},
           {sym:R`\vec u`,mean:"velocity vector (m/s)",href:"glossary.html#g-velocity"},
           {sym:R`\Gamma`,mean:"diffusion coefficient for φ",href:"glossary.html#g-fvm"},
           {sym:R`S_\phi`,mean:"source term for φ",href:"glossary.html#g-fvm"}],
     links:[{label:"Week 12",href:"week-12.html"},{label:"Finite volume method",href:"glossary.html#g-fvm"}],
     keywords:"finite volume method discretisation control volume mesh cell convection diffusion source algebraic"}
  ],

  /* =========================================================
     GLOSSARY
     ========================================================= */
  glossary:[
    /* ---- concepts ---- */
    {id:"g-pressure", term:"Pressure", sym:R`P`,
      def:R`Normal force per unit area (Pa), always acting perpendicular to a surface. Quoted as <em>absolute</em> (from a perfect vacuum) or <em>gauge</em> (relative to atmospheric); a negative gauge pressure is a vacuum. 1 bar = 10⁵ Pa, 1 atm = 101.325 kPa.`,
      see:[{label:"Gauge & absolute pressure",href:"equations.html#eq-gauge"}]},
    {id:"g-head", term:"Head", sym:R`h`,
      def:R`Energy expressed as an equivalent height of fluid (m), \(h = P/\rho g\). Convenient because every term in Bernoulli's equation then has the same units and can be drawn on the same diagram.`,
      see:[{label:"Hydrostatic pressure",href:"equations.html#eq-hydrostatic"}]},
    {id:"g-viscosity", term:"Viscosity", sym:R`\mu,\,\nu`,
      def:R`A fluid's resistance to flow, arising from internal friction between layers moving relative to each other. Dynamic viscosity \(\mu\) (Pa·s) appears in the stress law; kinematic viscosity \(\nu = \mu/\rho\) (m²/s) appears in the Reynolds number. An <em>inviscid</em> flow is the idealisation \(\mu = 0\).`,
      see:[{label:"Newton's law of viscosity",href:"equations.html#eq-newton-viscosity"}]},
    {id:"g-newtonian", term:"Newtonian fluid", sym:R`\tau=\mu\,du/dy`,
      def:R`A fluid whose shear stress is directly proportional to the velocity gradient, so viscosity is a constant. Water, air and most oils qualify. Non-Newtonian fluids do not: shear-thinning (paint, blood), shear-thickening (cornflour) and Bingham plastics (toothpaste) all have a viscosity that depends on the shear rate.`,
      see:[{label:"Newton's law of viscosity",href:"equations.html#eq-newton-viscosity"}]},
    {id:"g-no-slip", term:"No-slip condition", sym:R`—`,
      def:R`At a solid boundary the fluid moves with the surface — zero relative velocity. It holds for every real (viscous) fluid, and it is what creates boundary layers and hence all viscous drag.`,
      see:[{label:"Boundary layer",href:"glossary.html#g-boundary-layer"}]},
    {id:"g-pascal", term:"Pascal's law", sym:R`—`,
      def:R`Pressure applied to a confined fluid at rest is transmitted equally in all directions, and at a point the pressure is the same whichever plane you measure it on. The hydraulic press is the direct application.`,
      see:[{label:"Hydraulic press",href:"equations.html#eq-hydraulic-press"}]},
    {id:"g-centre-pressure", term:"Centre of pressure", sym:R`y_R`,
      def:R`The point through which the resultant hydrostatic force acts. Because pressure grows with depth, it always lies <em>below</em> the centroid of the surface — though the gap shrinks as the surface is submerged deeper.`,
      see:[{label:"Centre of pressure",href:"equations.html#eq-centre-pressure"}]},
    {id:"g-centroid", term:"Centroid", sym:R`y_C,\,h_C`,
      def:R`The geometric centre of an area. The pressure at the centroid equals the <em>average</em> pressure over a plane surface, which is why the resultant force is simply \(P_C A\).`,
      see:[{label:"Force on a plane surface",href:"equations.html#eq-hydrostatic-force"}]},
    {id:"g-second-moment", term:"Second moment of area", sym:R`I_{xx}`,
      def:R`\(I = \int y^2\,dA\) (m⁴) — how far an area's material is spread from an axis. Here it sets how far below the centroid the centre of pressure falls.`,
      see:[{label:"Centre of pressure",href:"equations.html#eq-centre-pressure"}]},
    {id:"g-buoyancy", term:"Buoyancy", sym:R`F_B`,
      def:R`The net upward force on an immersed body, equal to the weight of fluid displaced (Archimedes' principle) and acting through the centre of buoyancy — the centroid of the displaced volume.`,
      see:[{label:"Buoyant force",href:"equations.html#eq-buoyancy"}]},
    {id:"g-metacentre", term:"Metacentre", sym:R`M`,
      def:R`For a tilted floating body, the point where the new line of buoyant force crosses the original centreline. If the metacentre lies <em>above</em> the centre of gravity the couple rights the body and it is stable; below, and the tilt grows and it capsizes.`,
      see:[{label:"Buoyant force",href:"equations.html#eq-buoyancy"}]},
    {id:"g-control-volume", term:"Control volume", sym:R`CV`,
      def:R`A fixed region of space that fluid flows through, as opposed to a <em>system</em> (a fixed lump of fluid). The Reynolds transport theorem is what converts a law written for a system into one written for a control volume.`,
      see:[{label:"Continuity",href:"equations.html#eq-continuity"}]},
    {id:"g-streamline", term:"Streamline", sym:R`—`,
      def:R`A curve everywhere tangent to the velocity vector at an instant. No flow can cross a streamline, so a bundle of them forms a <em>streamtube</em> that behaves like a pipe with imaginary walls — which is what lets Bernoulli be applied along it.`,
      see:[{label:"Bernoulli equation",href:"equations.html#eq-bernoulli"}]},
    {id:"g-reynolds", term:"Reynolds number", sym:R`Re`,
      def:R`Inertial forces divided by viscous forces. Low \(Re\) means viscosity dominates and the flow is laminar and orderly; high \(Re\) means inertia dominates and the flow is turbulent. In a pipe, transition is near \(Re \approx 2300\).`,
      see:[{label:"Reynolds number",href:"equations.html#eq-reynolds"}]},
    {id:"g-vena-contracta", term:"Vena contracta", sym:R`A_2`,
      def:R`The narrowest point of a jet just downstream of an opening, where the streamlines have finished converging. Its area is smaller than the hole's — the ratio is the contraction coefficient — which is why the actual discharge falls short of the ideal.`,
      see:[{label:"Discharge coefficients",href:"equations.html#eq-discharge-coeff"}]},
    {id:"g-discharge-coeff", term:"Discharge coefficient", sym:R`C_d`,
      def:R`The single factor reconciling ideal Bernoulli theory with the measured flow, \(C_d = C_c C_v\) — the product of the contraction and velocity coefficients. Always less than one; about 0.6–0.65 for a sharp-edged orifice.`,
      see:[{label:"Discharge coefficients",href:"equations.html#eq-discharge-coeff"}]},
    {id:"g-ke-correction", term:"Kinetic-energy correction factor", sym:R`\alpha`,
      def:R`Corrects the velocity-head term when the profile is not uniform, since the mean of \(u^2\) is not \(\bar u^2\). About 2 for laminar pipe flow and 1.05 for turbulent — which is why it is often dropped for turbulent flow.`,
      see:[{label:"Extended Bernoulli",href:"equations.html#eq-extended-bernoulli"}]},
    {id:"g-navier-stokes", term:"Navier–Stokes equations", sym:R`—`,
      def:R`Newton's second law applied to a fluid particle, giving a set of nonlinear partial differential equations. No general analytical solution is known; a handful of simple geometries (Couette, Poiseuille) can be solved exactly, and everything else is numerical.`,
      see:[{label:"Navier–Stokes equations",href:"equations.html#eq-navier-stokes"}]},
    {id:"g-boundary-layer", term:"Boundary layer", sym:R`\delta`,
      def:R`The thin region near a surface where viscosity has slowed the flow, bounded conventionally where the velocity reaches 99% of the free stream. It starts laminar and may transition to turbulent; outside it the flow behaves as if inviscid.`,
      see:[{label:"Flow separation",href:"glossary.html#g-separation"}]},
    {id:"g-separation", term:"Flow separation", sym:R`—`,
      def:R`Where an adverse pressure gradient causes the boundary layer to detach from the surface, leaving a wide low-pressure wake and a large pressure drag. A turbulent boundary layer carries more momentum near the wall, so it separates <em>later</em> — which is why golf balls have dimples.`,
      see:[{label:"Drag & lift force",href:"equations.html#eq-drag-lift"}]},
    {id:"g-drag-coeff", term:"Drag & lift coefficients", sym:R`C_D,\,C_L`,
      def:R`Dimensionless force, obtained by dividing by dynamic pressure and a reference area (frontal for drag, planform for lift). They collapse experimental data across sizes and speeds, and generally depend on Reynolds number and shape.`,
      see:[{label:"Drag & lift force",href:"equations.html#eq-drag-lift"}]},
    {id:"g-fully-developed", term:"Fully developed flow", sym:R`—`,
      def:R`Far enough down a pipe that the boundary layers from the walls have met and the velocity profile stops changing with distance. Only then is the friction factor constant, which is what the Darcy–Weisbach equation assumes.`,
      see:[{label:"Darcy–Weisbach",href:"equations.html#eq-darcy-weisbach"}]},
    {id:"g-friction-factor", term:"Darcy friction factor", sym:R`f`,
      def:R`The dimensionless coefficient in the Darcy–Weisbach equation. Exactly \(64/Re\) in laminar flow; in turbulent flow it depends on Reynolds number <em>and</em> relative roughness, via the implicit Colebrook correlation or the Moody chart.`,
      see:[{label:"Friction factor",href:"equations.html#eq-friction-factor"}]},
    {id:"g-roughness", term:"Relative roughness", sym:R`\varepsilon/D`,
      def:R`The average height of the wall's surface irregularities divided by the pipe diameter. It has no effect in laminar flow, but in fully rough turbulent flow it alone sets the friction factor.`,
      see:[{label:"Friction factor",href:"equations.html#eq-friction-factor"}]},
    {id:"g-losses", term:"Major & minor losses", sym:R`h_f,\,h_L`,
      def:R`Major losses are friction along the straight pipe runs; minor losses are local losses at bends, valves, entries, exits and area changes. The names mislead — in a short pipe with many fittings the minor losses can dominate.`,
      see:[{label:"Minor losses",href:"equations.html#eq-minor-losses"}]},
    {id:"g-buckingham", term:"Buckingham Pi theorem", sym:R`\Pi`,
      def:R`A relationship among \(k\) dimensional variables spanning \(r\) primary dimensions can be reduced to one among \(k-r\) dimensionless groups. It turns an impossible experimental programme into a manageable one.`,
      see:[{label:"Buckingham Pi theorem",href:"equations.html#eq-buckingham"}]},
    {id:"g-similarity", term:"Similarity", sym:R`—`,
      def:R`Geometric similarity is the same shape; kinematic similarity the same velocity-field shape; dynamic similarity the same force ratios, which requires the governing dimensionless group to match. Only then does a model test predict the prototype.`,
      see:[{label:"Dynamic similarity",href:"equations.html#eq-similarity"}]},
    {id:"g-egl", term:"Energy & hydraulic grade lines", sym:R`EGL,\,HGL`,
      def:R`The EGL plots total head along a system and always falls in the flow direction except across a pump; the HGL sits one velocity head below it. Where the HGL falls below the pipe, the pressure is sub-atmospheric and cavitation becomes a risk.`,
      see:[{label:"Energy & hydraulic grade line",href:"equations.html#eq-egl-hgl"}]},
    {id:"g-operating-point", term:"Operating point", sym:R`—`,
      def:R`Where a pump's performance curve crosses the system curve — the only flow and head at which both the pump and the pipework are satisfied simultaneously.`,
      see:[{label:"Pump & turbine power",href:"equations.html#eq-pump-power"}]},
    {id:"g-hardy-cross", term:"Hardy Cross method", sym:R`\Delta Q`,
      def:R`An iterative solution for pipe networks: assume flows satisfying continuity at every node, compute the head-loss imbalance around each loop, apply a correction to the whole loop, and repeat until the imbalance vanishes.`,
      see:[{label:"Hardy Cross correction",href:"equations.html#eq-hardy-cross"}]},
    {id:"g-void-fraction", term:"Void fraction & holdup", sym:R`\alpha,\,H_L`,
      def:R`The fraction of a pipe's cross-section occupied by gas, and its complement the liquid holdup. Distinct from <em>quality</em>, which is a mass fraction — the two differ because the phases travel at different speeds.`,
      see:[{label:"Quality & void fraction",href:"equations.html#eq-quality-void"}]},
    {id:"g-superficial", term:"Superficial velocity", sym:R`u_{SG},\,u_{SL}`,
      def:R`The velocity a phase would have if it flowed alone through the whole pipe at its actual rate. Not a real velocity — the true phase velocity is higher — but it is the standard axis of flow-regime maps.`,
      see:[{label:"Superficial velocity",href:"equations.html#eq-superficial"}]},
    {id:"g-flow-regime", term:"Flow regime", sym:R`—`,
      def:R`The geometric arrangement the phases take up. Vertically: bubble, slug, churn then annular as gas rate rises. Horizontally, gravity adds stratified and wavy. The regime controls pressure drop and stability, so identifying it comes first.`,
      see:[{label:"Superficial velocity",href:"equations.html#eq-superficial"}]},
    {id:"g-fvm", term:"Finite volume method", sym:R`—`,
      def:R`The discretisation used by most CFD solvers: divide the domain into control volumes and integrate the conservation equations over each, so that every cell conserves mass, momentum and energy by construction.`,
      see:[{label:"Finite volume discretisation",href:"equations.html#eq-fvm"}]},
    {id:"g-mesh-independence", term:"Mesh independence", sym:R`—`,
      def:R`A result that stops changing as the mesh is refined. Demonstrating it — alongside convergence and validation against data — is what separates an engineering answer from a colourful picture.`,
      see:[{label:"Finite volume method",href:"glossary.html#g-fvm"}]},

    /* ---------------------------------------------------------------
       NOMENCLATURE — the recurring quantities. Every variable listed
       under an equation links to one of these, so you can hover any
       symbol on the equations page to see what it means.
       --------------------------------------------------------------- */
    {id:"g-density", term:"Density", sym:R`\rho`,
      def:R`Mass per unit volume (kg/m³); about 1000 for water and 1.2 for air. Specific gravity is this divided by the density of water, and specific weight is \(\rho g\).`,
      see:[{label:"Density & specific gravity",href:"equations.html#eq-density"}]},
    {id:"g-mass", term:"Mass", sym:R`m`,
      def:R`The amount of fluid (kg). Conserved absolutely, which is what the continuity equation expresses.`,
      see:[{label:"Continuity",href:"equations.html#eq-continuity"}]},
    {id:"g-mass-flow", term:"Mass flow rate", sym:R`\dot m`,
      def:R`Mass crossing a section per unit time (kg/s), \(\dot m = \rho A u\). Equal at every section of a steady flow, whether or not the fluid is incompressible.`,
      see:[{label:"Continuity",href:"equations.html#eq-continuity"}]},
    {id:"g-flow-rate", term:"Volumetric flow rate", sym:R`Q`,
      def:R`Volume passing a section per unit time (m³/s), \(Q = Au\). Constant along a steady incompressible flow, which is why area and velocity trade off against each other.`,
      see:[{label:"Continuity",href:"equations.html#eq-continuity"}]},
    {id:"g-velocity", term:"Velocity", sym:R`u`,
      def:R`Flow speed (m/s). In pipe work it is nearly always the <em>mean</em> velocity \(Q/A\), even though the real profile is parabolic (laminar) or blunt (turbulent).`,
      see:[{label:"Reynolds number",href:"equations.html#eq-reynolds"}]},
    {id:"g-area", term:"Area", sym:R`A`,
      def:R`Cross-sectional area normal to the flow, or the area of a submerged surface (m²).`,
      see:[{label:"Continuity",href:"equations.html#eq-continuity"}]},
    {id:"g-volume", term:"Volume", sym:R`V`,
      def:R`The space occupied by fluid (m³) — including the displaced volume that sets the buoyant force.`,
      see:[{label:"Buoyant force",href:"equations.html#eq-buoyancy"}]},
    {id:"g-force", term:"Force", sym:R`F`,
      def:R`A push on a surface or a body (N) — the resultant hydrostatic force on a gate, the drag on a body, or the reaction on a pipe bend from the momentum equation.`,
      see:[{label:"Momentum equation",href:"equations.html#eq-momentum"}]},
    {id:"g-power", term:"Power", sym:R`\dot W`,
      def:R`Rate of energy transfer (W). The hydraulic power exchanged with a fluid is \(\rho g Q h\); shaft power differs from it by the machine's efficiency.`,
      see:[{label:"Pump & turbine power",href:"equations.html#eq-pump-power"}]},
    {id:"g-efficiency", term:"Efficiency", sym:R`\eta`,
      def:R`Useful output over input. A pump draws more shaft power than it gives the fluid; a turbine delivers less shaft power than the fluid gives up. Which way the efficiency divides is the usual place to go wrong.`,
      see:[{label:"Pump & turbine power",href:"equations.html#eq-pump-power"}]},
    {id:"g-gravity", term:"Gravitational acceleration", sym:R`g`,
      def:R`9.81 m/s². Appears wherever weight matters — hydrostatics, buoyancy, elevation head and the Froude number.`,
      see:[{label:"Hydrostatic pressure",href:"equations.html#eq-hydrostatic"}]},
    {id:"g-elevation", term:"Elevation", sym:R`z`,
      def:R`Height above an arbitrary datum (m). Only differences matter, so choose the datum to make the algebra easy — usually the lower of the two points.`,
      see:[{label:"Bernoulli equation",href:"equations.html#eq-bernoulli"}]},
    {id:"g-length", term:"Length", sym:R`L`,
      def:R`A streamwise distance (m) — the run of pipe over which friction acts, or the characteristic length in a dimensionless group.`,
      see:[{label:"Darcy–Weisbach",href:"equations.html#eq-darcy-weisbach"}]},
    {id:"g-diameter", term:"Diameter", sym:R`D`,
      def:R`Pipe bore (m). It sets the Reynolds number, the relative roughness and — through the \(L/D\) term — the friction loss. For a non-circular duct use the hydraulic diameter.`,
      see:[{label:"Darcy–Weisbach",href:"equations.html#eq-darcy-weisbach"}]},
    {id:"g-radius", term:"Radius", sym:R`R,\,r`,
      def:R`\(R\) is the pipe radius and \(r\) the distance from the centreline. The Hagen–Poiseuille flow rate depends on \(R^4\), so pipe size matters enormously.`,
      see:[{label:"Hagen–Poiseuille",href:"equations.html#eq-poiseuille"}]},
    {id:"g-coordinate", term:"Coordinates", sym:R`x,\,y`,
      def:R`Position within the flow. \(y\) is usually measured normal to a surface — the direction the velocity gradient in Newton's law of viscosity is taken along.`,
      see:[{label:"Newton's law of viscosity",href:"equations.html#eq-newton-viscosity"}]},
    {id:"g-angle", term:"Angle", sym:R`\theta`,
      def:R`The inclination of a submerged surface to the horizontal, which converts a slant distance along the surface into a vertical depth via \(h = y\sin\theta\).`,
      see:[{label:"Force on a plane surface",href:"equations.html#eq-hydrostatic-force"}]},
    {id:"g-shear-stress", term:"Shear stress", sym:R`\tau`,
      def:R`Force per unit area acting tangent to a surface (Pa). At a wall it is what integrates up into skin-friction drag and pipe friction loss.`,
      see:[{label:"Newton's law of viscosity",href:"equations.html#eq-newton-viscosity"}]},
    {id:"g-time", term:"Time", sym:R`t`,
      def:R`The independent variable in unsteady terms. A <em>steady</em> flow is one where every property at a point is independent of \(t\) — which most of this course assumes.`,
      see:[{label:"Navier–Stokes equations",href:"equations.html#eq-navier-stokes"}]}
  ],

  /* =========================================================
     ASSESSMENTS — intentionally empty: archived subject.
     ========================================================= */
  assessments:[]
};
